Improve fixed scroll with animation
lcrojano/Giphy_Explorer pull request #43
Opened 2023-10-27 17:20 UTC by sergomen

https://github.com/lcrojano/Giphy_Explorer/assets/18175528/d1b818a2-da1a-43f6-95c2-34fbfe6db3af

2023-10-27 20:58 UTC, lcrojano approved these changes

2023-10-27 20:58 UTC, lcrojano commented on index.html
> +        logo = document.getElementById("logo");
Managing features through JavaScript is a great idea.

2023-10-27 21:08 UTC, lcrojano requested changes
Congratulations! Your PR successfully implements the requested feature. However, there is a conflict that needs to be avoided. Please check the lines that implement styles for the github link.

2023-10-27 21:08 UTC, lcrojano commented on styles/styles.css
> -  font-family: sans-serif;
The deletion of this particular lines will result in breaking the GitHub link feature which was introduced in issue #38.

2023-10-28 11:29 UTC, sergomen commented
Do I need to do something with these css lines?

2023-10-28 18:44 UTC, merged